################################################################################
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileType: OTHER
# SPDX-FileCopyrightText: (c) 2022, OpenGateware authors and contributors
################################################################################
name: Build/Release
################################################################################
# How to create a tag to launch the workflow
# git tag -a "0.1.0" -m "Release v0.1.0"
# git push origin --tags
################################################################################
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  synthesis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - pocket
    env:
      CORE: msx
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "🧰 Checkout Repository"
        uses: actions/checkout@v4

      - name: "🧰 Checkout Packybara"
        uses: actions/checkout@v4
        with:
          repository: "boogermann/publish"
          path: ".github/publish"

      - name: "🏗️ Compile Design"
        uses: raetro/quartus-flow@v1
        with:
          project: "${{ env.CORE }}_${{ matrix.target }}"
          version: "${{ matrix.target }}"

      - name: "🏗️ Create Packages and Release"
        env:
          TARGET: ${{ matrix.target }}
        run: |
          pip3 install -r .github/publish/requirements.txt
          python3 .github/publish/${{ matrix.TARGET }}.py
